---
title: "Open Science Toolbox"
subtitle: "A Collection of Resources to Facilitate Open Science Practices"
author:
- "Lutz Heil"
- "lheil@students.uni-mainz.de"
- "LMU Open Science Center"
date: "April 14, 2018"
fontsize: 12pt
site: bookdown::bookdown_site
documentclass: report
output:
  bookdown::pdf_book
subparagraph: true
---
# Preface {-}
The motivation to engage in a more transparent research and the actual implementation of Open Science practices into the research workflow can be two very distinct things. Work on the motivational side has been successfully done in various contexts (see section [_Key Papers_](#key_papers)). Here the focus rather lays on closing the intention-action gap. Providing an overview of handy Open Science tools and resources might facilitate the implementation of these practices and thereby foster Open Science on a practical level rather than on a theoretical.

So far, there is a vast body of helpful tools that can be used in order to foster Open Science practices. Without doubt, all of these tools add value to a more transparent research. But for reasons of clarity and to save time which would be consumed by trawling through the web, this toolbox aims at providing only a selection of links to these resources and tools. Our goal is to give a short overview on possibilities of how to enhance your Open Science practices without consuming too much of your time.

**How can I use the toolbox?**
If you're time is too valuable to check out the toolbox entirely, a first start is to read the first chapter [_Getting Started_](#getting_started). Though, the main body of the toolbox consists of the [_Resources for Researchers_](#res_researchers). Here you'll find Open Science resources ordered by the stage of the research cycle.
If you are interested in teaching about Open Science or if you search for workshop material to educate yourself, you might want to jump to chapter 3: [_Resources for Teaching_](#res_teaching). Finally there is a small chapter called [_Community_](#community) which can be helpful if you seek information on how to get involved and where to get Open Science news.

**Context.**
This toolbox has been created during my work at the [**Open Science Center (OSC)**](http://www.osc.uni-muenchen.de/index.html) of the Ludwig-Maximilians-Universität, Munich. This document is supposed to serve as a merger of all resources that are provided in the online toolbox (available on: [http://www.osc.uni-muenchen.de/toolbox/index.html](http://www.osc.uni-muenchen.de/toolbox/index.html)). Special thanks go to my supervisor [Felix Schönbrodt](http://www.osc.uni-muenchen.de/members/individual-members/schoenbrodt/index.html) who came up with the idea and made important contributions.

**Contribute.**
The toolbox raises no claim to completeness, it should rather serve as selection of tools. If you think there is (1) an important tool or article that should be included, (2) a broken link or citation, or (3) any other issue or question, please feel free to contact me and contribute to this toolbox: [lheil@students.uni-mainz.de](mailto:lheil@students.uni-mainz.de)


